export const transactionsData = [
  {
    id: 1,
    type: "Airtime",
    user: "Zainab A.",
    amount: "₦500",
    provider: "MTN",
    status: "Success",
    date: "June 25",
    time: "10:58 AM",
  },
  {
    id: 2,
    type: "Gift Card",
    user: "Emeka O.",
    amount: "$100",
    provider: "Amazon (Digital)",
    status: "Verified",
    date: "June 24",
    time: "1:39 PM",
  },
  {
    id: 3,
    type: "Electricity",
    user: "Dami K.",
    amount: "₦7,800",
    provider: "PHED",
    status: "Success",
    date: "June 23",
    time: "8:14 AM",
  },
  {
    id: 4,
    type: "Data",
    user: "Tolu A.",
    amount: "₦1,200",
    provider: "Airtel",
    status: "Failed",
    date: "June 23",
    time: "3:20 PM",
  },
  {
    id: 5,
    type: "Gift Card",
    user: "Ifeanyi N.",
    amount: "$50",
    provider: "Steam (Physical)",
    status: "Rejected",
    date: "June 22",
    time: "5:45 PM",
  },
  {
    id: 6,
    type: "Cable",
    user: "Bukola F.",
    amount: "₦5,500",
    provider: "GOtv",
    status: "Success",
    date: "June 22",
    time: "12:01 PM",
  },
  {
    id: 7,
    type: "Airtime",
    user: "Kabir M.",
    amount: "₦300",
    provider: "9mobile",
    status: "Success",
    date: "June 22",
    time: "7:55 PM",
  },
  {
    id: 8,
    type: "Gift Card",
    user: "Chioma E.",
    amount: "$25",
    provider: "iTunes",
    status: "Pending",
    date: "June 21",
    time: "10:30 AM",
  },
  {
    id: 9,
    type: "Data",
    user: "Precious T.",
    amount: "₦2,000",
    provider: "MTN",
    status: "Success",
    date: "June 20",
    time: "4:18 PM",
  },
  {
    id: 10,
    type: "Cable",
    user: "Musa L.",
    amount: "₦6,200",
    provider: "DStv",
    status: "Failed",
    date: "June 20",
    time: "9:22 AM",
  },
];
